version: 1.0
provider:
  name: openfaas
  gateway: http://172.31.0.121:8080
functions:
  entrust-ca:
    lang: golang-middleware
    handler: ./entrust-ca
    image: entrust-ca:latest
    environment_file:
      - certs.yml

  hello:
    lang: node12
    handler: ./hello
    image: hello:node12
